defaults:
  - isaaclab_stack_cube_ppo_openpi
  - override hydra/job_logging: stdout
  - _self_

runner:
  logger:
    experiment_name: "isaaclab_stack_cube_openpi_eval"
  only_eval: True
  val_check_interval: -1
  save_interval: -1

algorithm:
  eval_rollout_epoch: 1

env:
  eval:
    total_num_envs: 8
    max_episode_steps: 350
    max_steps_per_rollout_epoch: 350
    auto_reset: True
    ignore_terminations: True
    use_fixed_reset_state_ids: True
    video_cfg:
      save_video: True
      info_on_video: True
      video_base_dir: ${runner.logger.log_path}/video/eval
