defaults:
  - model/pi0@actor.model
  - training_backend/fsdp@actor.fsdp_config
  - override hydra/job_logging: stdout
  - _self_

hydra:
  run:
    dir: .
  output_subdir: null
  searchpath:
    - file://${oc.env:EMBODIED_PATH}/config/

cluster:
  num_nodes: 1
  component_placement:
    actor: 0-1

runner:
  task_type: sft
  logger:
    log_path: "../results"
    project_name: rlinf
    experiment_name: "isaaclab_sft_openpi"
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 30000
  max_steps: -1
  val_check_interval: -1
  save_interval: 5000

  resume_dir: null

data:
  # HF_LEROBOT_HOME; should be the parent directory of generated_simdata_full/
  train_data_paths: "/path/to/isaaclab_lerobot_home"

algorithm:
  adv_type: gae

actor:
  group_name: "ActorGroup"
  training_backend: "fsdp"
  micro_batch_size: 32
  global_batch_size: 2048
  seed: 42

  model:
    model_type: "openpi"
    precision: null
    model_path: "/path/to/openpi_base_or_sft_model_dir"
    num_action_chunks: 10
    action_dim: 7
    add_value_head: True
    openpi:
      config_name: "pi0_isaaclab"
      detach_critic_input: True

  optim:
    lr: 2.5e-5
    value_lr: 1.55e-4
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-08
    weight_decay: 1.0e-10
    clip_grad: 1.0
    warmup_style: "cosine"
    lr_warmup_steps: 1000
    total_training_steps: 30000

  fsdp_config:
    strategy: "fsdp"
    sharding_strategy: "no_shard"
    use_orig_params: False
    gradient_checkpointing: False
    cpu_offload: False
    mixed_precision:
      param_dtype: ${actor.model.precision}
      reduce_dtype: ${actor.model.precision}
      buffer_dtype: ${actor.model.precision}

reward:
  use_reward_model: False

critic:
  use_critic_model: False
